language: generic
sudo: required
services:
 - docker

before install:
 - docker build -t dako22/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true dako22/docker-react npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "ap-northeast-1"
 app: "docker-react"
 env: "Dockerreact-env"
 bucket_name: "elasticbeanstalk-ap-northeast-1-288075394530"\
 bucket_path: "docker-react"
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: "$AWS_SECRET_KEY"